version: '3.8'

services:
  api:
    container_name: products-api
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://admin:${MYSQL_PASSWORD}@mysql:3306/ecommerce
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "npx zenstack generate && npx prisma db push && npx prisma db seed && npm run start:dev -- --watch"

  web:
    container_name: products-web
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - VITE_API_URL=http://api:3002
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    depends_on:
      - api
    command: npm run dev

  mysql:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "--password=${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: 